-- Create SUB FACTOR columns in Barriers table if they don't exist

ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: INCOME LEVEL_Value" NUMERIC DEFAULT 0;
ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: INCOME LEVEL_Weight" NUMERIC DEFAULT 0;

ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: DISTANCE_Value" NUMERIC DEFAULT 1;
ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: DISTANCE_Weight" NUMERIC DEFAULT 0;

ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: TRUST_Value" NUMERIC DEFAULT 0;
ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: TRUST_Weight" NUMERIC DEFAULT 0;

ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: COSTS_Value" NUMERIC DEFAULT 0;
ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: COSTS_Weight" NUMERIC DEFAULT 0;

ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: REGISTRATION_Value" NUMERIC DEFAULT 0;
ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: REGISTRATION_Weight" NUMERIC DEFAULT 0;

ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Value" NUMERIC DEFAULT 0;
ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Weight" NUMERIC DEFAULT 0;

ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: FINANCIAL LITERACY_Value" NUMERIC DEFAULT 0;
ALTER TABLE "Barriers" ADD COLUMN IF NOT EXISTS "SUB FACTOR: FINANCIAL LITERACY_Weight" NUMERIC DEFAULT 0;
