-- Create Barriers data table with same structure as Usage and Access tables
CREATE TABLE IF NOT EXISTS public."Barriers" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "Project ID" UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  "Branch ID" UUID NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
  
  -- Main barrier data
  "BARRIERS_Value" NUMERIC,
  "BARRIERS_Weight" NUMERIC,
  "Barriers_Actual_Data" NUMERIC,
  
  -- SUB FACTOR: INCOME LEVEL
  "SUB FACTOR: INCOME LEVEL_Value" NUMERIC,
  "SUB FACTOR: INCOME LEVEL_Weight" NUMERIC,
  
  -- SUB FACTOR: DISTANCE
  "SUB FACTOR: DISTANCE_Value" NUMERIC,
  "SUB FACTOR: DISTANCE_Weight" NUMERIC,
  
  -- SUB FACTOR: TRUST
  "SUB FACTOR: TRUST_Value" NUMERIC,
  "SUB FACTOR: TRUST_Weight" NUMERIC,
  
  -- SUB FACTOR: COSTS
  "SUB FACTOR: COSTS_Value" NUMERIC,
  "SUB FACTOR: COSTS_Weight" NUMERIC,
  
  -- SUB FACTOR: REGISTRATION
  "SUB FACTOR: REGISTRATION_Value" NUMERIC,
  "SUB FACTOR: REGISTRATION_Weight" NUMERIC,
  
  -- SUB FACTOR: SOCIAL AND CULTURAL FACTORS
  "SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Value" NUMERIC,
  "SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Weight" NUMERIC,
  
  -- SUB FACTOR: FINANCIAL LITERACY
  "SUB FACTOR: FINANCIAL LITERACY_Value" NUMERIC,
  "SUB FACTOR: FINANCIAL LITERACY_Weight" NUMERIC,
  
  -- KPI: VALUE CHAIN DIVERSIFICATION RATE
  "KPI: VALUE CHAIN DIVERSIFICATION RATE_Value" NUMERIC,
  "KPI: VALUE CHAIN DIVERSIFICATION RATE_Weight" NUMERIC,
  
  -- KPI: STARTUP LEVEL RATE
  "KPI: STARTUP LEVEL RATE_Value" NUMERIC,
  "KPI: STARTUP LEVEL RATE_Weight" NUMERIC,
  
  -- KPI: ACCELERATION LEVEL RATE
  "KPI: ACCELERATION LEVEL RATE_Value" NUMERIC,
  "KPI: ACCELERATION LEVEL RATE_Weight" NUMERIC,
  
  -- KRI: FRAUD INCIDENT RATE
  "KRI: FRAUD INCIDENT RATE_Value" NUMERIC,
  "KRI: FRAUD INCIDENT RATE_Weight" NUMERIC,
  
  -- KRI: TRUST EROSION IN MFIs
  "KRI: TRUST EROSION IN MFIs_Value" NUMERIC,
  "KRI: TRUST EROSION IN MFIs_Weight" NUMERIC,
  
  -- KRI: MEMBERS LOAN COST
  "KRI: MEMBERS LOAN COST_Value" NUMERIC,
  "KRI: MEMBERS LOAN COST_Weight" NUMERIC,
  
  -- KRI: HAND IN HAND LOAN COST
  "KRI: HAND IN HAND LOAN COST_Value" NUMERIC,
  "KRI: HAND IN HAND LOAN COST_Weight" NUMERIC,
  
  -- KRI: MFI LOAN SERVICE COST
  "KRI: MFI LOAN SERVICE COST_Value" NUMERIC,
  "KRI: MFI LOAN SERVICE COST_Weight" NUMERIC,
  
  -- KRI: DOCUMENTATION DELAY RATE
  "KRI: DOCUMENTATION DELAY RATE_Value" NUMERIC,
  "KRI: DOCUMENTATION DELAY RATE_Weight" NUMERIC,
  
  -- KRI: GENDER BASED BARRIER RATE
  "KRI: GENDER BASED BARRIER RATE_Value" NUMERIC,
  "KRI: GENDER BASED BARRIER RATE_Weight" NUMERIC,
  
  -- KRI: FAMILY AND COMMUNITY BARRIER RATE
  "KRI: FAMILY AND COMMUNITY BARRIER RATE_Value" NUMERIC,
  "KRI: FAMILY AND COMMUNITY BARRIER RATE_Weight" NUMERIC,
  
  -- KRI: TRAINEE DROPOUT RATE(1)
  "KRI: TRAINEE DROPOUT RATE(1)_Value" NUMERIC,
  "KRI: TRAINEE DROPOUT RATE(1)_Weight" NUMERIC,
  
  -- KRI: TRAINER DROPOUT RATE(2)
  "KRI: TRAINER DROPOUT RATE(2)_Value" NUMERIC,
  "KRI: TRAINER DROPOUT RATE(2)_Weight" NUMERIC,
  
  -- KRI: CARRICULUM RELEVANCE COMPLAINT RATE
  "KRI: CARRICULUM RELEVANCE COMPLAINT RATE_Value" NUMERIC,
  "KRI: CARRICULUM RELEVANCE COMPLAINT RATE_Weight" NUMERIC,
  
  -- KRI: LOW KNOWLEDGE RETENTION RATE
  "KRI: LOW KNOWLEDGE RETENTION RATE_Value" NUMERIC,
  "KRI: LOW KNOWLEDGE RETENTION RATE_Weight" NUMERIC,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX idx_barriers_project_id ON public."Barriers"("Project ID");
CREATE INDEX idx_barriers_branch_id ON public."Barriers"("Branch ID");
CREATE INDEX idx_barriers_created_at ON public."Barriers"(created_at);

-- Enable Row Level Security
ALTER TABLE public."Barriers" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Barriers table
-- Policy 1: Admins can manage all barriers data
CREATE POLICY "Admins can manage all barriers data" ON public."Barriers"
  AS PERMISSIVE
  FOR ALL
  TO authenticated
  USING (auth.jwt() ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- Policy 2: Users can view barriers for their branch
CREATE POLICY "Users can view barriers for their branch" ON public."Barriers"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (
    "Branch ID" IN (
      SELECT branch_id FROM public.profiles WHERE id = auth.uid()
    )
    OR auth.jwt() ->> 'role' = 'admin'
  );

COMMIT;
