-- Populate BARRIERS_Value for all existing records
-- BARRIERS_Value = weighted sum of all SUB FACTOR values

UPDATE "Barriers"
SET "BARRIERS_Value" = ROUND(
  (COALESCE("SUB FACTOR: INCOME LEVEL_Value", 0) * COALESCE("SUB FACTOR: INCOME LEVEL_Weight", 0)) +
  (COALESCE("SUB FACTOR: DISTANCE_Value", 0) * COALESCE("SUB FACTOR: DISTANCE_Weight", 0)) +
  (COALESCE("SUB FACTOR: TRUST_Value", 0) * COALESCE("SUB FACTOR: TRUST_Weight", 0)) +
  (COALESCE("SUB FACTOR: COSTS_Value", 0) * COALESCE("SUB FACTOR: COSTS_Weight", 0)) +
  (COALESCE("SUB FACTOR: REGISTRATION_Value", 0) * COALESCE("SUB FACTOR: REGISTRATION_Weight", 0)) +
  (COALESCE("SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Value", 0) * COALESCE("SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Weight", 0)) +
  (COALESCE("SUB FACTOR: FINANCIAL LITERACY_Value", 0) * COALESCE("SUB FACTOR: FINANCIAL LITERACY_Weight", 0)),
  4
)
WHERE "Barriers"."id" IS NOT NULL;
