SELECT "Branch ID", "Project ID", "BARRIERS_Value",
  "SUB FACTOR: INCOME LEVEL_Value", "SUB FACTOR: INCOME LEVEL_Weight",
  "SUB FACTOR: DISTANCE_Value", "SUB FACTOR: DISTANCE_Weight",
  "SUB FACTOR: TRUST_Value", "SUB FACTOR: TRUST_Weight",
  "SUB FACTOR: COSTS_Value", "SUB FACTOR: COSTS_Weight",
  "SUB FACTOR: REGISTRATION_Value", "SUB FACTOR: REGISTRATION_Weight",
  "SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Value", "SUB FACTOR: SOCIAL AND CULTURAL FACTORS_Weight",
  "SUB FACTOR: FINANCIAL LITERACY_Value", "SUB FACTOR: FINANCIAL LITERACY_Weight"
FROM "Barriers"
LIMIT 5;
