-- Verify Barriers table KPI values have been populated
SELECT 
  "Project ID",
  "Branch ID",
  "KPI: VALUE CHAIN DIVERSIFICATION RATE_Value",
  "KPI: VALUE CHAIN DIVERSIFICATION RATE_Weight",
  "KPI: STARTUP LEVEL RATE_Value",
  "KPI: STARTUP LEVEL RATE_Weight",
  "KPI: ACCELERATION LEVEL RATE_Value",
  "KPI: ACCELERATION LEVEL RATE_Weight"
FROM "Barriers"
WHERE "KPI: VALUE CHAIN DIVERSIFICATION RATE_Value" IS NOT NULL
  OR "KPI: STARTUP LEVEL RATE_Value" IS NOT NULL
  OR "KPI: ACCELERATION LEVEL RATE_Value" IS NOT NULL
ORDER BY "Project ID", "Branch ID";
